FROM ubuntu:latest

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y curl; apt-get install -y kafkacat
RUN apt-get install -y jq; apt-get install -y bsdmainutils

RUN curl https://downloads.mongodb.com/compass/mongodb-mongosh_1.3.1_arm64.deb -o mongosh.deb && \
    dpkg --install mongosh.deb

COPY connect-setup /
RUN chmod +x /initialize-container.sh

RUN rm mongosh.deb
