#
# FROM confluentinc/cp-kafka-connect:latest
#
# This one is for arm64..
# https://github.com/OneCricketeer/apache-kafka-connect-docker
FROM cricketeerone/apache-kafka-connect:latest

COPY connect/mongo-kafka-connect-1.7.0-all.jar /app/libs/