FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y curl; apt-get install -y kafkacat
RUN apt-get install -y jq; apt-get install -y bsdmainutils

# install mongosh
RUN curl https://downloads.mongodb.com/compass/mongodb-mongosh_1.3.1_arm64.deb -o mongosh.deb && \
    dpkg --install mongosh.deb

COPY shell /
RUN chmod +x /initialize-container.sh

# Cleanup
RUN rm mongosh.deb
